---

- hosts: all
  become: true
  tasks:

    - name: update repository
      dnf:
        update_cache: yes

    - name: install httpd package
      dnf:
        name: httpd
        state: absent
    - name: add php support for httpd
      dnf:
        name: php
