---

- hosts: all
  become: true
  tasks:

    - name: install updates (Red Hat)
      dnf:
        update_only: yes

    - name: install httpd package
      dnf:
        name:
          - httpd
          - php
          - vim
        state: latest
        update_cache: yes
      when: ansible_distribution == "RedHat"

    - name: install apache2 package
      dnf:
        apt:
          - apache2
          - vim
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

