---
- name: Update BIND zone file names
  hosts: dns_servers
  become: true
  tasks:


    - name: Update named.conf zone file reference
      replace:
        path: /etc/named.conf
        regexp: 'cbm-net.cbm.gov.mm.zone'
        replace: 'drcbm-net.cbm.gov.mm.zone'

    - name: Update named.conf reverse zone file reference
      replace:
        path: /etc/named.conf
        regexp: '200.254.10.rev'
        replace: '201.254.10.rev'

    - name: Restart named service
      service:
        name: named
        state: restarted
        enabled: yes
